<a href="https://colab.research.google.com/github/BozhkoIryna/Python-projects/blob/main/Python_for_DA_Module_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#  завантажуємо бібліотеки Python

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Завантажую датасет

from google.colab import drive
drive.mount("/content/drive")

%cd /content/drive/MyDrive/dataset

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/dataset

#**Data overview**
Розуміння даних та їх змісту.

In [ ]:
# дані по продуктам
products = pd.read_csv("products.csv")
products.head()

     id        item_type
0  2103           Cereal
1  7940        Household
2  2455          Clothes
3  1270        Beverages
4  8681  Office Supplies

In [ ]:
print(f"Products shape:", products.shape) #кількість рядків і колонок
products.info() #загальна інформація про датасет
print(products.dtypes) #тип даних у кожному стовпчику

Products shape: (12, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         12 non-null     int64
 1   item_type  12 non-null     object
dtypes: int64(1), object(1)
memory usage: 324.0+ bytes
id            int64
item_type    object
dtype: object

In [ ]:
# дані по продуктам
countries = pd.read_csv("countries.csv")
countries.head()

             name alpha-2 alpha-3   region       sub-region
0     Afghanistan      AF     AFG     Asia    Southern Asia
1   Åland Islands      AX     ALA   Europe  Northern Europe
2         Albania      AL     ALB   Europe  Southern Europe
3         Algeria      DZ     DZA   Africa  Northern Africa
4  American Samoa      AS     ASM  Oceania        Polynesia

In [ ]:
print(f"Countries shape:", countries.shape) #кількість рядків і колонок
countries.info() #загальна інформація про датасет
print(countries.dtypes) #тип даних у кожному стовпчику

Countries shape: (249, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        249 non-null    object
 1   alpha-2     248 non-null    object
 2   alpha-3     249 non-null    object
 3   region      248 non-null    object
 4   sub-region  248 non-null    object
dtypes: object(5)
memory usage: 9.9+ KB
name          object
alpha-2       object
alpha-3       object
region        object
sub-region    object
dtype: object

In [ ]:
# дані по подіям
events = pd.read_csv("events.csv")
events.head()

,Order ID,Order Date,Ship Date,Order Priority,Country Code,Product ID,Sales Channel,Units Sold,Unit Price,Unit Cost
0,100640618,10/8/2014,10/18/2014,M,NOR,2103,Online,650.0,205.70,117.11
1,100983083,8/11/2016,8/11/2016,C,SRB,2103,Offline,1993.0,205.70,117.11
2,101025998,7/18/2014,8/11/2014,M,NaN,7940,Online,4693.0,668.27,502.54
3,102230632,5/13/2017,6/13/2017,L,MNE,2455,Online,1171.0,109.28,35.84
4,103435266,8/11/2012,9/18/2012,H,SRB,1270,Offline,7648.0,47.45,31.79

In [ ]:
print(f"Events shape:", events.shape) #кількість рядків і колонок
events.info() #загальна інформація про датасет
print(events.dtypes)  #тип даних у кожному стовпчику

Events shape: (1330, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1330 entries, 0 to 1329
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        1330 non-null   int64
 1   Order Date      1330 non-null   object
 2   Ship Date       1330 non-null   object
 3   Order Priority  1330 non-null   object
 4   Country Code    1248 non-null   object
 5   Product ID      1330 non-null   int64
 6   Sales Channel   1330 non-null   object
 7   Units Sold      1328 non-null   float64
 8   Unit Price      1330 non-null   float64
 9   Unit Cost       1330 non-null   float64
dtypes: float64(3), int64(2), object(5)
memory usage: 104.0+ KB
Order ID            int64
Order Date         object
Ship Date          object
Order Priority     object
Country Code       object
Product ID          int64
Sales Channel      object
Units Sold        float64
Unit Price        float64
Unit Cost         float64
dtype: object

##**Змінні**
####**Products**
   id - ідентифікатор товару

   item_type - назва товару
####**Countries**
   name - назва країни

   alpha-2 - дволітерні коди країн

   alpha-3 - трьохлітерні коди країн

   region - назва регіону

   sub-region - назва субрегіону
####**Events**
   Order ID - ідентифікатор замовлення

   Order Date -  дата замовлення
   
   Ship Date - дата доставки
   
   Order Priority - пріоритет замовлення
   
   Country Code - код країни
   
   Product ID - ідентифікатор товару
   
   Sales Channel - канал продажу
   
   Units Sold - кількість проданого товару
   
   Unit Price - вартість товару
   
   Unit Cost - витрати на товар

   **Таблиці можна пояднати завдяки таким змінним:**

Events. Country Code >>> Countries. alpha-3

Events. Product ID >>> Products. id

#**Data cleaning**
Робота із пропущеними даними, некоректними даними, аномаліями.

## Перевірка на наявність пропущених значень у кожній таблиці, оцінюю їх долю, оцінюю причини їх виникнення.
Заповнюю або видаляю пропущені значення.

In [ ]:
#кількість пропущених значень в products
print(products.isna().sum())

id           0
item_type    0
dtype: int64

In [ ]:
#кількість пропущених значень в countries
print(countries.isna().sum())

name          0
alpha-2       1
alpha-3       0
region        1
sub-region    1
dtype: int64

In [ ]:
#доля пропущенних значень
print(countries.isna().sum() / countries.shape[0] * 100)

name          0.000000
alpha-2       0.401606
alpha-3       0.000000
region        0.401606
sub-region    0.401606
dtype: float64

In [ ]:
#перевіряємо, в яких рядках є пропущені дані.
missing_rows = countries[countries.isna().any(axis=1)]
print(missing_rows)

           name alpha-2 alpha-3  region          sub-region
8    Antarctica      AQ     ATA     NaN                 NaN
153     Namibia     NaN     NAM  Africa  Sub-Saharan Africa

In [ ]:
#змінюю пропущені дані на логічно вірні
countries["region"].fillna("Antarctica", inplace=True)
countries["sub-region"].fillna("Antarctica", inplace=True)
countries["alpha-2"].fillna("NA", inplace=True)

print(countries.isna().sum())

name          0
alpha-2       0
alpha-3       0
region        0
sub-region    0
dtype: int64

<ipython-input-89-1190fc0dc8b2>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  countries["region"].fillna("Antarctica", inplace=True)
<ipython-input-89-1190fc0dc8b2>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  countries["sub-region"].fillna("Antarctica", inplace=True)
<ipython-input-89-1190fc0dc8b2>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  countries["alpha-2"].fillna("NA", inplace=True)

In [ ]:
#перейменуємо назви стовпців events таким чином, щоб вони не містили великих літер, і були у вигляді snake_case
events.columns = events.columns.str.lower().str.replace(" ", "_")
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1330 entries, 0 to 1329
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        1330 non-null   int64
 1   order_date      1330 non-null   object
 2   ship_date       1330 non-null   object
 3   order_priority  1330 non-null   object
 4   country_code    1248 non-null   object
 5   product_id      1330 non-null   int64
 6   sales_channel   1330 non-null   object
 7   units_sold      1328 non-null   float64
 8   unit_price      1330 non-null   float64
 9   unit_cost       1330 non-null   float64
dtypes: float64(3), int64(2), object(5)
memory usage: 104.0+ KB

In [ ]:
#кількість пропущених значень в events
print(events.isna().sum())
#доля пропущенних значень
print(events.isna().sum() / events.shape[0] * 100)

order_id           0
order_date         0
ship_date          0
order_priority     0
country_code      82
product_id         0
sales_channel      0
units_sold         2
unit_price         0
unit_cost          0
dtype: int64
order_id          0.000000
order_date        0.000000
ship_date         0.000000
order_priority    0.000000
country_code      6.165414
product_id        0.000000
sales_channel     0.000000
units_sold        0.150376
unit_price        0.000000
unit_cost         0.000000
dtype: float64

In [ ]:
#перевіряємо, в яких рядках є пропущені дані.
missing_rows = events[events.isna().any(axis=1)]
print(missing_rows)

       order_id order_date  ship_date order_priority country_code  product_id  \
2     101025998  7/18/2014  8/11/2014              M          NaN        7940
13    104548490   1/1/2014   1/5/2014              M          NaN        7331
26    117929494  1/24/2015   3/2/2015              H          NaN        4594
29    118859469   6/2/2011   7/1/2011              L          NaN        8969
43    126948583  5/24/2017   7/9/2017              C          NaN        7331
...         ...        ...        ...            ...          ...         ...
1213  919922006  8/27/2011  9/18/2011              L          NaN        4594
1220  922564303  3/17/2017   4/2/2017              L          NaN        7940
1250  941061675   3/8/2017  3/20/2017              M          NaN        5988
1296  975080668  7/23/2017  8/20/2017              C          NaN        5988
1317  989102828  6/11/2012   7/8/2012              L          NaN        4594

     sales_channel  units_sold  unit_price  unit_cost
2           Online      4693.0      668.27     502.54
13          Online      7076.0      255.28     159.42
26         Offline      6813.0        9.33       6.92
29         Offline      2013.0      152.58      97.44
43          Online      5762.0      255.28     159.42
...            ...         ...         ...        ...
1213        Online      4219.0        9.33       6.92
1220       Offline      6134.0      668.27     502.54
1250       Offline      9917.0      154.06      90.93
1296       Offline      6893.0      154.06      90.93
1317        Online      6362.0        9.33       6.92

[84 rows x 10 columns]

In [ ]:
#змінюю пропущене значення на загальне "Unknown"
events["country_code"].fillna("Unknown", inplace=True)
# видаляю рядки, що мають пропущені значення в Units Sold
events.dropna(subset=["units_sold"], inplace=True)
print(events.isna().sum())

order_id          0
order_date        0
ship_date         0
order_priority    0
country_code      0
product_id        0
sales_channel     0
units_sold        0
unit_price        0
unit_cost         0
dtype: int64

<ipython-input-93-546ff1de5de5>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  events["country_code"].fillna("Unknown", inplace=True)

## Перевірка, чи всі типи даних розпізнаються коректно. Є розбіжності, тому роблю перетворення типів у колонках.

In [ ]:
#Order Date та   Ship Date мають невірний формат object, потрібно змінити на datetime
events["order_date"] = pd.to_datetime(events["order_date"], errors='coerce')

print(events["order_date"].dtypes)

events["ship_date"] = pd.to_datetime(events["ship_date"])
print(events["ship_date"].dtypes)
events.info()

datetime64[ns]
datetime64[ns]
<class 'pandas.core.frame.DataFrame'>
Index: 1328 entries, 0 to 1329
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        1328 non-null   int64
 1   order_date      1328 non-null   datetime64[ns]
 2   ship_date       1328 non-null   datetime64[ns]
 3   order_priority  1328 non-null   object
 4   country_code    1328 non-null   object
 5   product_id      1328 non-null   int64
 6   sales_channel   1328 non-null   object
 7   units_sold      1328 non-null   float64
 8   unit_price      1328 non-null   float64
 9   unit_cost       1328 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(3)
memory usage: 114.1+ KB

## Дослідження даних на наявність дублікатів. Виконую перетворення для усунення дублікатів.

In [ ]:
# Перевірка на наявність дублікатів у products
duplicate_rows = products.duplicated()
print(duplicate_rows)
print(duplicate_rows.sum())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool
0

In [ ]:
# Перевірка на наявність дублікатів у countries
duplicate_rows = countries.duplicated()
print(duplicate_rows)
print(duplicate_rows.sum())

0      False
1      False
2      False
3      False
4      False
       ...
244    False
245    False
246    False
247    False
248    False
Length: 249, dtype: bool
0

In [ ]:
# Перевірка на наявність дублікатів у events
duplicate_rows = events.duplicated()
print(duplicate_rows)
print(duplicate_rows.sum())

0       False
1       False
2       False
3       False
4       False
        ...
1325    False
1326    False
1327    False
1328    False
1329    False
Length: 1328, dtype: bool
0

In [ ]:
# Сума логічних значень дорівнює 0, а це означає, що усі значення — False. Отже, дублікати відсутні.

## Дослідження даних на наявність аномалій.
Аномалій не виявлено

In [ ]:
#основні характеристики набору даних
products.describe()

                id
count    12.000000
mean   5802.166667
std    2937.985452
min    1270.000000
25%    2959.000000
50%    6659.500000
75%    8390.000000
max    8969.000000

In [ ]:
#основні характеристики набору даних
countries.describe()

               name alpha-2 alpha-3  region          sub-region
count           249     249     249     249                 249
unique          249     249     249       6                  18
top     Afghanistan      AF     AFG  Africa  Sub-Saharan Africa
freq              1       1       1      60                  53

In [ ]:
#основні характеристики набору даних
events.describe()

,order_id,order_date,ship_date,product_id,units_sold,unit_price,unit_cost
count,1.328000e+03,1328,1328,1328.000000,1328.000000,1328.000000,1328.000000
mean,5.416231e+08,2013-10-11 22:28:54.939759104,2013-11-05 17:22:02.891566336,5787.775602,4952.201807,264.913245,187.211521
min,1.006406e+08,2010-01-01 00:00:00,2010-01-10 00:00:00,1270.000000,2.000000,9.330000,6.920000
25%,3.213291e+08,2011-12-14 06:00:00,2012-01-02 00:00:00,3127.000000,2356.750000,81.730000,35.840000
50%,5.399925e+08,2013-10-15 12:00:00,2013-11-05 12:00:00,5988.000000,4962.000000,154.060000,97.440000
75%,7.547357e+08,2015-08-29 12:00:00,2015-10-04 18:00:00,8681.000000,7459.500000,437.200000,263.330000
max,9.998797e+08,2017-07-23 00:00:00,2017-08-31 00:00:00,8969.000000,9999.000000,668.270000,524.960000
std,2.573496e+08,NaN,NaN,2820.635702,2905.198996,217.386320,176.187801

#**Data analysis and visualization**
Аналіз та візуалізація даних, знаходження цінних інсайтів.

##З’єднання трьох таблиць в один датафрейм. Видаляю непотрібні для аналізу колонки. Роблю перейменування колонок.

In [ ]:
# перейменування  колонки id в датафреймі products на product_id

products.rename(columns={"id": "product_id"}, inplace=True)
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  12 non-null     int64
 1   item_type   12 non-null     object
dtypes: int64(1), object(1)
memory usage: 324.0+ bytes

In [ ]:
# з’єднання events та products в один датафрейм та
left_join = pd.merge(events, products, on="product_id", how="left")
print(left_join)

       order_id order_date  ship_date order_priority country_code  product_id  \
0     100640618 2014-10-08 2014-10-18              M          NOR        2103
1     100983083 2016-08-11 2016-08-11              C          SRB        2103
2     101025998 2014-07-18 2014-08-11              M      Unknown        7940
3     102230632 2017-05-13 2017-06-13              L          MNE        2455
4     103435266 2012-08-11 2012-09-18              H          SRB        1270
...         ...        ...        ...            ...          ...         ...
1323  994504153 2017-01-10 2017-01-13              M          SWE        4594
1324  994978797 2014-12-05 2015-01-02              H          ITA        1270
1325  996754205 2010-09-20 2010-09-22              L          RUS        7331
1326  998043382 2010-06-15 2010-07-03              H          MLT        8293
1327  999879729 2012-03-31 2012-05-06              M          ALB        7940

     sales_channel  units_sold  unit_price  unit_cost  item_type
0           Online       650.0      205.70     117.11     Cereal
1          Offline      1993.0      205.70     117.11     Cereal
2           Online      4693.0      668.27     502.54  Household
3           Online      1171.0      109.28      35.84    Clothes
4          Offline      7648.0       47.45      31.79  Beverages
...            ...         ...         ...        ...        ...
1323        Online      4734.0        9.33       6.92     Fruits
1324       Offline      5192.0       47.45      31.79  Beverages
1325       Offline       574.0      255.28     159.42  Baby Food
1326        Online      2070.0      437.20     263.33  Cosmetics
1327       Offline      5486.0      668.27     502.54  Household

[1328 rows x 11 columns]

In [ ]:
# перейменування  колонки alpha-3 в датафреймі countries на country_code
countries.rename(columns={"alpha-3": "country_code"}, inplace=True)
countries.rename(columns={"name": "country_name"}, inplace=True)
countries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country_name  249 non-null    object
 1   alpha-2       249 non-null    object
 2   country_code  249 non-null    object
 3   region        249 non-null    object
 4   sub-region    249 non-null    object
dtypes: object(5)
memory usage: 9.9+ KB

In [ ]:
# з’єднання events, products та countries в один датафрейм
full_data = pd.merge(left_join, countries, on="country_code", how="left")
print(left_join)

       order_id order_date  ship_date order_priority country_code  product_id  \
0     100640618 2014-10-08 2014-10-18              M          NOR        2103
1     100983083 2016-08-11 2016-08-11              C          SRB        2103
2     101025998 2014-07-18 2014-08-11              M      Unknown        7940
3     102230632 2017-05-13 2017-06-13              L          MNE        2455
4     103435266 2012-08-11 2012-09-18              H          SRB        1270
...         ...        ...        ...            ...          ...         ...
1323  994504153 2017-01-10 2017-01-13              M          SWE        4594
1324  994978797 2014-12-05 2015-01-02              H          ITA        1270
1325  996754205 2010-09-20 2010-09-22              L          RUS        7331
1326  998043382 2010-06-15 2010-07-03              H          MLT        8293
1327  999879729 2012-03-31 2012-05-06              M          ALB        7940

     sales_channel  units_sold  unit_price  unit_cost  item_type
0           Online       650.0      205.70     117.11     Cereal
1          Offline      1993.0      205.70     117.11     Cereal
2           Online      4693.0      668.27     502.54  Household
3           Online      1171.0      109.28      35.84    Clothes
4          Offline      7648.0       47.45      31.79  Beverages
...            ...         ...         ...        ...        ...
1323        Online      4734.0        9.33       6.92     Fruits
1324       Offline      5192.0       47.45      31.79  Beverages
1325       Offline       574.0      255.28     159.42  Baby Food
1326        Online      2070.0      437.20     263.33  Cosmetics
1327       Offline      5486.0      668.27     502.54  Household

[1328 rows x 11 columns]

In [ ]:
full_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        1328 non-null   int64
 1   order_date      1328 non-null   datetime64[ns]
 2   ship_date       1328 non-null   datetime64[ns]
 3   order_priority  1328 non-null   object
 4   country_code    1328 non-null   object
 5   product_id      1328 non-null   int64
 6   sales_channel   1328 non-null   object
 7   units_sold      1328 non-null   float64
 8   unit_price      1328 non-null   float64
 9   unit_cost       1328 non-null   float64
 10  item_type       1328 non-null   object
 11  country_name    1246 non-null   object
 12  alpha-2         1246 non-null   object
 13  region          1246 non-null   object
 14  sub-region      1246 non-null   object
dtypes: datetime64[ns](2), float64(3), int64(2), object(8)
memory usage: 155.8+ KB

In [ ]:
# # видалення зайвих стовпців
# full_data = full_data.drop("country_code", axis=1)
full_data = full_data.drop("alpha-2", axis=1)
# full_data = full_data.drop("alpha-2_x", axis=1)
# full_data = full_data.drop("alpha-2_y", axis=1)
# full_data = full_data.drop("region_y", axis=1)
# full_data = full_data.drop("sub-region_y", axis=1)
# full_data = full_data.drop("country_name_y", axis=1)

In [ ]:
full_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        1328 non-null   int64
 1   order_date      1328 non-null   datetime64[ns]
 2   ship_date       1328 non-null   datetime64[ns]
 3   order_priority  1328 non-null   object
 4   country_code    1328 non-null   object
 5   product_id      1328 non-null   int64
 6   sales_channel   1328 non-null   object
 7   units_sold      1328 non-null   float64
 8   unit_price      1328 non-null   float64
 9   unit_cost       1328 non-null   float64
 10  item_type       1328 non-null   object
 11  country_name    1246 non-null   object
 12  region          1246 non-null   object
 13  sub-region      1246 non-null   object
dtypes: datetime64[ns](2), float64(3), int64(2), object(7)
memory usage: 145.4+ KB

In [ ]:
# перейменування  колонок датафреймі та самого датафрейма
data = full_data
data.rename(columns={"country_name_x": "country_name"}, inplace=True)
data.rename(columns={"region_x": "region"}, inplace=True)
data.rename(columns={"sub-region_x": "sub-region"}, inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        1328 non-null   int64
 1   order_date      1328 non-null   datetime64[ns]
 2   ship_date       1328 non-null   datetime64[ns]
 3   order_priority  1328 non-null   object
 4   country_code    1328 non-null   object
 5   product_id      1328 non-null   int64
 6   sales_channel   1328 non-null   object
 7   units_sold      1328 non-null   float64
 8   unit_price      1328 non-null   float64
 9   unit_cost       1328 non-null   float64
 10  item_type       1328 non-null   object
 11  country_name    1246 non-null   object
 12  region          1246 non-null   object
 13  sub-region      1246 non-null   object
dtypes: datetime64[ns](2), float64(3), int64(2), object(7)
memory usage: 145.4+ KB

In [ ]:
# Збереження у форматі CSV
data.to_csv('data.csv', index=False)